
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'ar';

export const translations = {
  en: {
    nav_home: "Home",
    nav_market: "Products",
    nav_meals: "Ready Meals",
    nav_kitchen: "Recipes",
    nav_about: "About",
    nav_pricing: "Pricing",
    featured: "Featured This Week",
    featured_sub: "Discover our weekly selection of premium gluten-free products.",
    bundle_title: "Chef's Special Bundle",
    bundle_desc: "Complete weekly meal plan",
    limited_time: "LIMITED TIME",
    order_now: "Order Now",
    add_to_cart: "Add to Cart",
    all: "All",
    pantry: "Pantry",
    bakery: "Bakery",
    snack: "Snack",
    kitchen_title: "Glutivia Kitchen",
    meals_title: "Fresh Ready-to-Eat Meals",
    meals_sub: "Gourmet meals prepared in our 100% gluten-free facility using Glutivia ingredients. Just heat and eat.",
    ingredients: "Ingredients",
    processing: "Processing...",
    proceed_checkout: "Proceed to Checkout",
    clear_cart: "Clear Cart",
    total: "Total",
    cart_empty: "Your cart is empty",
    cart_empty_sub: "Looks like you haven't added any gluten-free goodies yet.",
    continue_shopping: "Continue Shopping",
    hero_title_1: "DISCOVER YOUR",
    hero_title_2: "Gluten-Free Paradise",
    hero_sub: "Safe, delicious, and certified gluten-free recipes, products, and ready-made meals delivered to your door",
    explore_recipes: "Explore Recipes",
    shop_products: "Shop Products",
    why_choose: "Why Choose Glutivia?",
    our_promise: "Our Promise",
    join_community: "Join the Glutivia Community",
    start_shopping: "Start Shopping",
    community_title: "What Our Community Says",
    community_sub: "Hear from those who have transformed their lives with Glutivia.",
    footer_desc: "Making gluten-free living accessible, delicious, and worry-free. Certified products, fresh meals, and AI-powered culinary inspiration.",
    shop: "Shop",
    pantry_essentials: "Pantry Essentials",
    fresh_meals: "Fresh Meals",
    snacks: "Snacks",
    bakery_footer: "Bakery",
    company: "Company",
    contact: "Contact",
    sustainability: "Sustainability",
    blog: "Blog",
    rights_reserved: "All rights reserved.",
    recipes_header: "Delicious Gluten-Free Recipes",
    recipes_subheader: "Explore our collection of tested and approved recipes, all with detailed instructions and ingredient costs.",
    collection_badge: "Recipe Collection",
    view_recipe: "View Recipe",
    recipe_close: "Close",
    
    // Static Recipes Titles
    rec_msemen: "Moroccan Gluten-Free Msemen",
    rec_tabbouleh: "Quinoa Tabbouleh Salad",
    rec_pancakes: "Almond Flour Pancakes",
    rec_tagine: "Chickpea Tagine",
    rec_cookies: "Coconut Flour Cookies",
    rec_pasta: "Zucchini Noodle Pasta",
    rec_harira: "Gluten-Free Moroccan Harira",
    rec_peppers: "Quinoa Stuffed Bell Peppers",
    rec_roast_chicken: "Lemon Herb Roast Chicken",
    rec_bastilla: "GF Seafood Bastilla Rolls",
    rec_brownies: "Sweet Potato Brownies",
    rec_pizza: "Cauliflower Crust Pizza",
    
    // Ready Meals Titles
    meal_stroganoff: "GF Beef Stroganoff",
    meal_teriyaki: "Teriyaki Chicken Bowl",
    meal_pumpkin: "Creamy Pumpkin Soup",
    meal_curry: "Vegan Lentil Curry",
    meal_paella: "GF Seafood Paella",
    meal_moussaka: "GF Veggie Moussaka",
    meal_meatballs: "GF Turkey Meatballs & Zoodles",
    meal_quinoa_stuffed: "Mediterranean Stuffed Eggplant",

    badge_easy: "EASY",
    badge_15min: "15 MIN",
    badge_popular: "POPULAR",
    badge_chef: "CHEF PICK",
    badge_sweet: "SWEET",
    badge_lowcarb: "LOW CARB",
    badge_classic: "CLASSIC",
    badge_healthy: "HEALTHY",
    badge_family: "FAMILY",
    
    diff_easy: "Easy",
    diff_medium: "Medium",
    diff_hard: "Hard",
    
    nut_protein: "Protein",
    nut_carbs: "Carbs",
    nut_fat: "Fat",

    ai_section_title: "Can't find what you're looking for?",
    ai_section_desc: "Use our AI Chef to generate a custom recipe based on ingredients you have at home.",
    ai_title: "AI Kitchen Assistant",
    ai_sub: "Enter the ingredients you have, and let our AI Chef create a custom gluten-free recipe for you.",
    input_label: "What ingredients do you have?",
    input_placeholder: "e.g. Chicken breast, quinoa, bell peppers, lemon...",
    meal_type: "Meal Type",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    dessert: "Dessert",
    thinking: "Thinking...",
    generate_btn: "Generate Recipe",
    developing: "Developing photo...",
    instructions: "Instructions",
    ai_error: "Failed to generate recipe. Please check your API key or try again.",
    prep_time: "Prep Time",
    difficulty: "Difficulty",

    why_glutivia: "WHY GLUTIVIA",
    about_text: "At Glutivia, we understand the challenges of living with gluten intolerance. That's why we've created a comprehensive platform that brings together everything you need for a safe, delicious, and fulfilling gluten-free lifestyle. From carefully tested recipes to certified products and ready-made meals, we're here to make your daily meals easier, safer, and more enjoyable.",
    stat_recipes: "Certified Recipes",
    stat_products: "Trusted Products",
    stat_satisfaction: "Customer Satisfaction",
    stat_community: "Community Support",
    
    services_title: "Everything You Need",
    services_title_2: "For Gluten-Free Living",
    services_eyebrow: "OUR SERVICES",
    
    serv_1_title: "Simple Recipes",
    serv_1_desc: "Access 5000+ tested gluten-free recipes with step-by-step instructions, nutritional info, and DH pricing for ingredients",
    
    serv_2_title: "Certified Products",
    serv_2_desc: "Browse our curated selection of 300+ gluten-free products, all certified and available with transparent DH pricing",
    
    serv_3_title: "Ready-to-Order Meals",
    serv_3_desc: "Pre-made gluten-free meals delivered fresh to your door, starting from 45 DH per meal",

    pricing_title: "Simple, Transparent Pricing",
    pricing_sub: "Choose the plan that fits your gluten-free lifestyle.",
    plan_free: "Explorer",
    plan_pro: "Pro Member",
    plan_family: "Family Bundle",
    per_month: "/ month",
    feature_check: "Access to Recipes",
    feature_ai: "AI Chef (Limited)",
    feature_delivery: "Free Delivery",
    feature_discount: "10% Product Discount",
    select_plan: "Select Plan",
    current_plan: "Current Plan",
  },
  fr: {
    nav_home: "Accueil",
    nav_market: "Produits",
    nav_meals: "Repas Prêts",
    nav_kitchen: "Recettes",
    nav_about: "À Propos",
    nav_pricing: "Tarifs",
    featured: "En Vedette Cette Semaine",
    featured_sub: "Découvrez notre sélection hebdomadaire de produits sans gluten premium.",
    bundle_title: "Pack Spécial Chef",
    bundle_desc: "Plan repas complet pour la semaine",
    limited_time: "TEMPS LIMITÉ",
    order_now: "Commander",
    add_to_cart: "Ajouter au Panier",
    all: "Tout",
    pantry: "Épicerie",
    bakery: "Boulangerie",
    snack: "Snack",
    kitchen_title: "Cuisine Glutivia",
    meals_title: "Repas Frais Prêts-à-Manger",
    meals_sub: "Repas gastronomiques préparés dans notre installation 100% sans gluten. Il suffit de chauffer et manger.",
    ingredients: "Ingrédients",
    processing: "Traitement...",
    proceed_checkout: "Passer à la Caisse",
    clear_cart: "Vider le Panier",
    total: "Total",
    cart_empty: "Votre panier est vide",
    cart_empty_sub: "Il semble que vous n'ayez pas encore ajouté de produits sans gluten.",
    continue_shopping: "Continuer mes Achats",
    hero_title_1: "DÉCOUVREZ VOTRE",
    hero_title_2: "Paradis Sans Gluten",
    hero_sub: "Recettes, produits et plats cuisinés sûrs, délicieux et certifiés sans gluten livrés à votre porte",
    explore_recipes: "Explorer les Recettes",
    shop_products: "Acheter des Produits",
    why_choose: "Pourquoi Choisir Glutivia ?",
    our_promise: "Notre Promesse",
    join_community: "Rejoignez la Communauté Glutivia",
    start_shopping: "Commencer les Achats",
    community_title: "Ce Que Dit Notre Communauté",
    community_sub: "Découvrez les témoignages de ceux qui ont transformé leur vie avec Glutivia.",
    footer_desc: "Rendre la vie sans gluten accessible, délicieuse et sans souci. Produits certifiés, repas frais et inspiration culinaire par IA.",
    shop: "Boutique",
    pantry_essentials: "Essentiels du Garde-manger",
    fresh_meals: "Repas Frais",
    snacks: "En-cas",
    bakery_footer: "Boulangerie",
    company: "Entreprise",
    contact: "Contact",
    sustainability: "Durabilité",
    blog: "Blog",
    rights_reserved: "Tous droits réservés.",
    recipes_header: "Délicieuses Recettes Sans Gluten",
    recipes_subheader: "Explorez notre collection de recettes testées et approuvées, avec instructions détaillées et coûts.",
    collection_badge: "Collection de Recettes",
    view_recipe: "Voir la Recette",
    recipe_close: "Fermer",

    rec_msemen: "Msemen Marocain Sans Gluten",
    rec_tabbouleh: "Salade Taboulé au Quinoa",
    rec_pancakes: "Pancakes à la Farine d'Amande",
    rec_tagine: "Tajine aux Pois Chiches",
    rec_cookies: "Cookies à la Farine de Coco",
    rec_pasta: "Pâtes de Courgettes",
    rec_harira: "Harira Marocaine Sans Gluten",
    rec_peppers: "Poivrons Farcis au Quinoa",
    rec_roast_chicken: "Poulet Rôti Citron et Herbes",
    rec_bastilla: "Mini Bastilla aux Fruits de Mer SG",
    rec_brownies: "Brownies à la Patate Douce",
    rec_pizza: "Pizza à Croûte de Chou-Fleur",

    meal_stroganoff: "Bœuf Stroganoff SG",
    meal_teriyaki: "Bol de Poulet Teriyaki",
    meal_pumpkin: "Velouté de Potiron Crémeux",
    meal_curry: "Curry de Lentilles Végan",
    meal_paella: "Paella aux Fruits de Mer SG",
    meal_moussaka: "Moussaka Végétarienne SG",
    meal_meatballs: "Boulettes de Dinde et Zoodles SG",
    meal_quinoa_stuffed: "Aubergine Farcie Méditerranéenne",

    badge_easy: "FACILE",
    badge_15min: "15 MIN",
    badge_popular: "POPULAIRE",
    badge_chef: "CHOIX DU CHEF",
    badge_sweet: "DOUCEUR",
    badge_lowcarb: "FAIBLE EN GLUCIDES",
    badge_classic: "CLASSIQUE",
    badge_healthy: "SAIN",
    badge_family: "FAMILLE",
    
    diff_easy: "Facile",
    diff_medium: "Moyen",
    diff_hard: "Difficile",

    nut_protein: "Protéines",
    nut_carbs: "Glucides",
    nut_fat: "Lipides",

    ai_section_title: "Vous ne trouvez pas ce que vous cherchez ?",
    ai_section_desc: "Utilisez notre Chef IA pour générer une recette personnalisée avec vos ingrédients.",
    ai_title: "Assistant Cuisine IA",
    ai_sub: "Entrez vos ingrédients et laissez notre chef IA créer une recette sans gluten personnalisée.",
    input_label: "Quels ingrédients avez-vous ?",
    input_placeholder: "ex: Blanc de poulet, quinoa, poivrons, citron...",
    meal_type: "Type de repas",
    breakfast: "Petit-déjeuner",
    lunch: "Déjeuner",
    dinner: "Dîner",
    dessert: "Dessert",
    thinking: "Réflexion...",
    generate_btn: "Générer la Recette",
    developing: "Développement photo...",
    instructions: "Instructions",
    ai_error: "Échec de la génération. Veuillez vérifier votre clé API ou réessayer.",
    prep_time: "Temps",
    difficulty: "Difficulté",

    why_glutivia: "POURQUOI GLUTIVIA",
    about_text: "Chez Glutivia, nous comprenons les défis de la vie avec une intolérance au gluten. C'est pourquoi nous avons créé une plateforme complète qui rassemble tout ce dont vous avez besoin pour un mode de vie sans gluten sûr, délicieux et épanouissant.",
    stat_recipes: "Recettes Certifiées",
    stat_products: "Produits de Confiance",
    stat_satisfaction: "Satisfaction Client",
    stat_community: "Support Communautaire",
    
    services_title: "Tout Ce Dont Vous Avez Besoin",
    services_title_2: "Pour Vivre Sans Gluten",
    services_eyebrow: "NOS SERVICES",
    
    serv_1_title: "Recettes Simples",
    serv_1_desc: "Accédez à plus de 5000 recettes sans gluten testées avec instructions étape par étape et informations nutritionnelles",
    
    serv_2_title: "Produits Certifiés",
    serv_2_desc: "Parcourez notre sélection de plus de 300 produits sans gluten, tous certifiés et disponibles avec des prix transparents",
    
    serv_3_title: "Repas Prêts-à-Commander",
    serv_3_desc: "Repas sans gluten préparés livrés frais à votre porte, à partir de 45 DH par repas",

    pricing_title: "Tarification Simple",
    pricing_sub: "Choisissez le plan qui correspond à votre mode de vie.",
    plan_free: "Explorateur",
    plan_pro: "Membre Pro",
    plan_family: "Pack Famille",
    per_month: "/ mois",
    feature_check: "Accès aux Recettes",
    feature_ai: "Chef IA (Limité)",
    feature_delivery: "Livraison Gratuite",
    feature_discount: "10% de Réduction",
    select_plan: "Choisir",
    current_plan: "Actuel",
  },
  ar: {
    nav_home: "الرئيسية",
    nav_market: "المنتجات",
    nav_meals: "وجبات جاهزة",
    nav_kitchen: "وصفات",
    nav_about: "من نحن",
    nav_pricing: "الأسعار",
    featured: "مميز هذا الأسبوع",
    featured_sub: "اكتشف تشكيلتنا الأسبوعية من المنتجات الفاخرة الخالية من الغلوتين.",
    bundle_title: "باقة الشيف الخاصة",
    bundle_desc: "خطة وجبات أسبوعية كاملة",
    limited_time: "لفترة محدودة",
    order_now: "اطلب الآن",
    add_to_cart: "أضف إلى السلة",
    all: "الكل",
    pantry: "مؤونة",
    bakery: "مخبز",
    snack: "وجبات خفيفة",
    kitchen_title: "مطبخ غلوتيفيا",
    meals_title: "وجبات طازجة جاهزة للأكل",
    meals_sub: "وجبات فاخرة محضرة في منشأتنا الخالية تماماً من الغلوتين. فقط سخن وكل.",
    ingredients: "المكونات",
    processing: "جاري المعالجة...",
    proceed_checkout: "متابعة الدفع",
    clear_cart: "إفراغ السلة",
    total: "المجموع",
    cart_empty: "سلة التسوق فارغة",
    cart_empty_sub: "يبدو أنك لم تضف أي منتجات خالية من الغلوتين بعد.",
    continue_shopping: "مواصلة التسوق",
    hero_title_1: "اكتشف",
    hero_title_2: "جنتك الخالية من الغلوتين",
    hero_sub: "وصفات ومنتجات ووجبات جاهزة آمنة ولذيذة ومعتمدة خالية من الغلوتين تصل إلى باب منزلك",
    explore_recipes: "استكشف الوصفات",
    shop_products: "تسوق المنتجات",
    why_choose: "لماذا تختار غلوتيفيا؟",
    our_promise: "وعدنا",
    join_community: "انضم إلى مجتمع غلوتيفيا",
    start_shopping: "ابدأ التسوق",
    community_title: "ماذا يقول مجتمعنا",
    community_sub: "استمع إلى أولئك الذين غيروا حياتهم مع غلوتيفيا.",
    footer_desc: "جعل الحياة الخالية من الغلوتين سهلة ولذيذة وخالية من القلق. منتجات معتمدة، وجبات طازجة، وإلهام طهي مدعوم بالذكاء الاصطناعي.",
    shop: "تسوق",
    pantry_essentials: "أساسيات المؤونة",
    fresh_meals: "وجبات طازجة",
    snacks: "وجبات خفيفة",
    bakery_footer: "مخبز",
    company: "الشركة",
    contact: "اتصل بنا",
    sustainability: "الاستدامة",
    blog: "المدونة",
    rights_reserved: "جميع الحقوق محفوظة.",
    recipes_header: "وصفات لذيذة خالية من الغلوتين",
    recipes_subheader: "استكشف مجموعتنا من الوصفات المختبرة والمعتمدة، مع تعليمات مفصلة وتكاليف المكونات.",
    collection_badge: "مجموعة الوصفات",
    view_recipe: "عرض الوصفة",
    recipe_close: "إغلاق",

    rec_msemen: "مسمن مغربي خالي من الغلوتين",
    rec_tabbouleh: "سلطة تبولة الكينوا",
    rec_pancakes: "بان كيك دقيق اللوز",
    rec_tagine: "طاجن الحمص",
    rec_cookies: "كوكيز دقيق جوز الهند",
    rec_pasta: "مكرونة الكوسا",
    rec_harira: "حريرة مغربية خالية من الغلوتين",
    rec_peppers: "فلفل محشو بالكينوا",
    rec_roast_chicken: "دجاج مشوي بالليمون والأعشاب",
    rec_bastilla: "بسطيلة فواكه البحر خالية من الغلوتين",
    rec_brownies: "براونيز البطاطا الحلوة",
    rec_pizza: "بيتزا بعجينة القرنبيط",

    meal_stroganoff: "بيف ستروغانوف خالي من الغلوتين",
    meal_teriyaki: "وعاء دجاج تيرياكي",
    meal_pumpkin: "شوربة اليقطين الكريمية",
    meal_curry: "كاري العدس النباتي",
    meal_paella: "باييلا فواكه البحر خالية من الغلوتين",
    meal_moussaka: "مسقعة نباتية خالية من الغلوتين",
    meal_meatballs: "كرات ديك رومي مع زoodles",
    meal_quinoa_stuffed: "باذنجان محشو متوسطي",

    badge_easy: "سهل",
    badge_15min: "15 دقيقة",
    badge_popular: "شائع",
    badge_chef: "اختيار الشيف",
    badge_sweet: "حلوى",
    badge_lowcarb: "قليل الكربوهيدرات",
    badge_classic: "كلاسيكي",
    badge_healthy: "صحي",
    badge_family: "عائلي",
    
    diff_easy: "سهل",
    diff_medium: "متوسط",
    diff_hard: "صعب",

    nut_protein: "بروتين",
    nut_carbs: "كربوهيدرات",
    nut_fat: "دهون",

    ai_section_title: "لم تجد ما تبحث عنه؟",
    ai_section_desc: "استخدم الشيف الذكي لإنشاء وصفة مخصصة بناءً على المكونات التي لديك.",
    ai_title: "مساعد المطبخ الذكي",
    ai_sub: "أدخل المكونات التي لديك، ودع طاهينا الذكي يبتكر لك وصفة مخصصة خالية من الغلوتين.",
    input_label: "ما هي المكونات التي لديك؟",
    input_placeholder: "مثال: صدر دجاج، كينوا، فلفل، ليمون...",
    meal_type: "نوع الوجبة",
    breakfast: "إفطار",
    lunch: "غداء",
    dinner: "عشاء",
    dessert: "تحلية",
    thinking: "جاري التفكير...",
    generate_btn: "إنشاء وصفة",
    developing: "جاري تحميض الصورة...",
    instructions: "التعليمات",
    ai_error: "فشل إنشاء الوصفة. يرجى التحقق من مفتاح API أو المحاولة مرة أخرى.",
    prep_time: "الوقت",
    difficulty: "الصعوبة",

    why_glutivia: "لماذا غلوتيفيا",
    about_text: "في غلوتيفيا، نفهم تحديات العيش مع حساسية الغلوتين. لهذا السبب أنشأنا منصة شاملة تجمع كل ما تحتاجه لنمط حياة خالٍ من الغلوتين آمن ولذيذ.",
    stat_recipes: "وصفات معتمدة",
    stat_products: "منتجات موثوقة",
    stat_satisfaction: "رضا العملاء",
    stat_community: "دعم المجتمع",
    
    services_title: "كل ما تحتاجه",
    services_title_2: "لحياة خالية من الغلوتين",
    services_eyebrow: "خدماتنا",
    
    serv_1_title: "وصفات بسيطة",
    serv_1_desc: "الوصول إلى 5000+ وصفة خالية من الغلوتين مع تعليمات خطوة بخطوة ومعلومات غذائية",
    
    serv_2_title: "منتجات معتمدة",
    serv_2_desc: "تصفح مجموعتنا المختارة من 300+ منتج خالي من الغلوتين، جميعها معتمدة وبأسعار شفافة",
    
    serv_3_title: "وجبات جاهزة للطلب",
    serv_3_desc: "وجبات خالية من الغلوتين جاهزة للتوصيل طازجة إلى باب منزلك، تبدأ من 45 درهم للوجبة",

    pricing_title: "أسعار بسيطة وشفافة",
    pricing_sub: "اختر الخطة التي تناسب نمط حياتك.",
    plan_free: "مستكشف",
    plan_pro: "عضو محترف",
    plan_family: "باقة العائلة",
    per_month: "/ شهر",
    feature_check: "الوصول للوصفات",
    feature_ai: "شيف ذكي (محدود)",
    feature_delivery: "توصيل مجاني",
    feature_discount: "خصم 10٪ على المنتجات",
    select_plan: "اختر",
    current_plan: "الحالي",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['en']) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: keyof typeof translations['en']) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
